//Note: ClassCat5 triggers for a Paladin


IF
    ClassLevelGT(Myself,WIZARD,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 WIZARD~)
END

IF
    ClassLevelGT(Myself,WIZARD,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 WIZARD~)
END






IF
    ClassLevelGT(Myself,PRIEST,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 PRIEST~)
END

IF
    ClassLevelGT(Myself,PRIEST,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 PRIEST~)
END


IF
    ClassLevelGT(Myself,PRIEST,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 PRIEST~)
END







IF
    ClassLevelGT(Myself,5,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 `ClassCat5`~)
END



IF
    ClassLevelGT(Myself,5,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 `ClassCat5`~)
END

IF
    ClassLevelGT(Myself,5,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 `ClassCat5`~)
END


IF
    ClassLevelGT(Myself,5,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 `ClassCat5`~)
END






IF
    ClassLevelGT(Myself,6,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 `ClassCat6`~)
END

IF
    ClassLevelGT(Myself,6,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 `ClassCat6`~)
END


IF
    ClassLevelGT(Myself,6,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 `ClassCat6`~)
END










IF
    ClassLevelGT(Myself,7,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 `ClassCat7`~)
END

IF
    ClassLevelGT(Myself,7,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 `ClassCat7`~)
END


IF
    ClassLevelGT(Myself,7,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 `ClassCat7`~)
END










IF
    ClassLevelGT(Myself,8,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 `ClassCat8`~)
END

IF
    ClassLevelGT(Myself,8,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 `ClassCat8`~)
END


IF
    ClassLevelGT(Myself,8,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 `ClassCat8`~)
END










IF
    ClassLevelGT(Myself,9,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 `ClassCat9`~)
END

IF
    ClassLevelGT(Myself,9,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 `ClassCat9`~)
END


IF
    ClassLevelGT(Myself,9,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 `ClassCat9`~)
END












IF
    ClassLevelGT(Myself,10,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 `ClassCat10`~)
END

IF
    ClassLevelGT(Myself,10,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 `ClassCat10`~)
END


IF
    ClassLevelGT(Myself,10,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 `ClassCat10`~)
END












IF
    ClassLevelGT(Myself,12,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 `ClassCat12`~)
END

IF
    ClassLevelGT(Myself,12,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 `ClassCat12`~)
END


IF
    ClassLevelGT(Myself,12,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 `ClassCat12`~)
END

