IF
    ClassLevelGT(Myself,WIZARD,20)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 21 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,19)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 20 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,18)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 19 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,17)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 18 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,16)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 17 WIZARD~)
END



IF
    ClassLevelGT(Myself,WIZARD,15)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 16 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,14)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 15 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,13)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 14 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,12)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 13 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,11)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 12 WIZARD~)
END

IF
    ClassLevelGT(Myself,WIZARD,10)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 11 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,9)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 10 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,8)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 9 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,7)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 8 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,6)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 7 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,5)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 6 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,4)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 5 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,3)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 4 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,2)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 3 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,1)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 2 WIZARD~)
END


IF
    ClassLevelGT(Myself,WIZARD,0)
THEN
    RESPONSE #100
        DisplayString(Myself, ~Level 1 WIZARD~)
END

