/*************************************************************
*   This file drives the installation of "missing" potions   *
*   (spells which would make logical sense as potions)       *
*   that do not exist in the game.                           *
*************************************************************/

INCLUDE ~./%MOD_FOLDER%/comp/missing-potions/process-potion-registry.tph~

INCLUDE ~./%MOD_FOLDER%/comp/missing-potions/tinkering.tph~
