/***********
* Scribing kit stuff *
***********/

//Make a cutscene file for copying the spell into spell book
COMPILE ~./%MOD_FOLDER%/comp/crafting-scroll/BAF/bzctbkcp.baf~

//NOTE: tested the compilation of the dialog in its initial state. Attempt to mutate it next...
INCLUDE ~./%MOD_FOLDER%/comp/crafting-scroll/2E/generate_scribe_dialog.tph~

//compile the new dialog (with huge mutated edits)
COMPILE ~./%MOD_FOLDER%/comp/crafting-scroll/2E/BZMSCSC.d~
