DEFINE_ACTION_FUNCTION ~fn_bz_lookup_costs_potion~
    INT_VAR
        tier = 0
    RET
        cost
    BEGIN
        OUTER_SET cost = "-1"

        ACTION_PHP_EACH ~costs_potion_tier~
            AS ~keys~ => ~value~
                BEGIN
                    //if the tradition and spell level match...
                    ACTION_IF (~%keys_0%~ = tier) THEN BEGIN OUTER_SET cost = value END
                END
    END
